name: 'rpmbuild'
description: 'Build RPM packages'
author: 'loganbickmore'
inputs:
  spec_file:
    description: 'path to spec file'
    required: true
    default: '*.spec'
  _topdir:
    description: 'rpm top dir'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
