name: 'Build and Test Action'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run lint
      - run: npm run test
      - run: npm run build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Test action
      - uses: ./
        id: rpm_build
        with:
          spec_file: example/.rpm/hello-typescript.spec
          _topdir: example/.rpm/build

      # Echo Outputs
      - run: echo '${{ toJSON(steps.rpm_build.outputs)' }}
      - run: pwd
      - run: ls $(dirname ${{ steps.rpm_build.outputs.rpm_path }})

      # Upload artifact for inspection
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.rpm_build.outputs.rpm_name }}
          path: ${{ steps.rpm_build.outputs.rpm_path }}
          # path: example/.rpm/build/RPMS/noarch/${{ steps.rpm_build.outputs.rpm_name }}
          # path: example/.rpm/build/RPMS/**/*.rpm
